### ISSUE TITLE
Stuck on searching for your details...

### ISSUE THREAD

**Issue by 0ceanSlim** [DanConwayDev/ngit-cli#3]
When I ngit login I input nsec and password to encrypt and it never gets past searching for details. Same thing now when running ngit claim I type password after prompt to login and get stuck on searching for your details. 

This is with the windows exe.

**Comment by DanConwayDev** [comment]
Thanks for reporting. I cannot replicate this on linux but it could be the same issue as #1. I'll spin up a Windows box tomorrow and investigate.

**Comment by monty888** [comment]
similar -  long search then I got this err - 

> searching for your details...
> Error: metadata cannot be found in kind 0 event content
> 
> Caused by:
>     Json: invalid type: integer `1696156935`, expected a string at line 1 column 530

I did update my profile meta in Amethyst just to see if that might fix but no help

**Comment by DanConwayDev** [comment]
@0ceanSlim I believe you were encountering the same issue as #1 which I hopefully fixed with e0f543e8 now in v0.1.1. See  https://github.com/DanConwayDev/ngit-cli/issues/1#issuecomment-1912766548 for more. Please can you try the latest version available from http://gitworkshop.dev/ngit?

@monty888 you are experiencing a different issue, which @sectore also encountered and he fixed this by bumping a dependancy which is live in v0.1.1 thanks to his PR.

Thanks so much for trying the tool and I'd love your feedback if you manage to try it again. 

It is obviously at an early stage. I rushed sharing it as the conversation of how to git over nostr ignited earlier this week.

**Comment by 0ceanSlim** [comment]
Awesome, I will try it out when I get home. I do not know rust so I can't contribute there but I know enough to compile (cargo) the source so I can always test. :)

**Comment by DanConwayDev** [comment]
Any sort of feedback is super useful. is something broken? what do you like about it? what don't you like about it? Did something happen that you didn't expect? ideas for improvements....

**Comment by monty888** [comment]
updated to v0.01, seems to get further but now I get the following output trying to make a claim
> searching for your details...
> fetching from wss://purplepages.es/
> fetching from wss://relay.damus.io/
> fetching from wss://nostr-pub.wellorder.net/
> fetching from wss://nos.lol/
> fetched 2 events from wss://nos.lol/
> fetched 2 events from wss://nostr-pub.wellorder.net/
> fetched 1 events from wss://relay.damus.io/
> failed to get events from relay wss://purplepages.es/
> Error: user metadata should always have name

**Comment by 0ceanSlim** [comment]
I logged good now. Scraped all my relays, even my private one. Now I'm trying to push but get "checkout a branch associated with a pr first"  How do I checkout a branch?

**Comment by 0ceanSlim** [comment]
Oh wait! I see my repo in the domain! https://gitworkshop.dev/repo/4983e79036dde0b6d299715a621466cd97c00fb9/

**Comment by DanConwayDev** [comment]
> @0ceanSlim I logged good now. Scraped all my relays, even my private one. Now I'm trying to push but get "checkout a branch associated with a pr first" How do I checkout a branch?

What were you expecting to happen when you ran `ngit push`?

If you are expecting it to create a PR / patch-set with from the commits that are ahead of your local main/master branch then the command is `ngit prs create`. see https://gitworkshop.dev/ngit for the available commands and what they do.

ngit uses your relay list as a starting point for the repository relays. It doesnt dynamically update to reflect own relay list. You can update the repository relay list by updating the `maintainers.yaml` file then running `ngit claim` again. Note: I'd recommend leaving blaster in until the tool is a bit more mature.

I regret adding the relay functionality in so early. Its premature optimisation and causing a lot of issues that I don't experience using relays spun up in dev environment.

**Comment by 0ceanSlim** [comment]
Trying to prs list now because I see the open pr on your domain but I'm getting stuck in the terminal after it fetches from the relays.

**Comment by DanConwayDev** [comment]
ngit v0.1.1 is not handling connecting to so many relays.

As a temporary fix you could delete all but a few relays in `maintainers.yaml` and push that to the remote.

I sent the the pr event but it crashed before it could send the commit/patch. 

ngit always uses the relays listed in `maintainers.yaml` file if its present. and it wont allow me to `ngit push` unless the repo is in a clean state (ie maintainers.yaml isn't modified) so I can't just modify it myself.

**Comment by DanConwayDev** [comment]
> @monty888 Error: user metadata should always have name

Fixed in 4589d06023b21a49a4d82fa24228a3879300cd7f. I'll push v0.1.2 with this soon.

**Comment by 0ceanSlim** [comment]
compiled [4589d06](https://github.com/DanConwayDev/ngit-cli/commit/4589d06023b21a49a4d82fa24228a3879300cd7f). I was able to fetch the PR this time but when I selected it and enter it started fetching and hung again. It also seems to still be fetching from relays that are not in my maintainers yaml anymore.

**Comment by DanConwayDev** [comment]
It looks like there is a bug in a dependency. a failing connection attempt to a relay doesn't timeout but instead has high cpu usage. The behavior is the same when the timeout is explicitly set to 1 second rather than relying on the default.

I'll look at fixing the dependency when I next get a moment.

**Comment by monty888** [comment]
> > @monty888 Error: user metadata should always have name
> 
> Fixed in [4589d06](https://github.com/DanConwayDev/ngit-cli/commit/4589d06023b21a49a4d82fa24228a3879300cd7f). I'll push v0.1.2 with this soon.

This worked, though unfortunately when I first went to claim I did it from the ngit source dir so I now claimed monstr twice! One points to ngit and the other correctly to my monstr rep.

**Comment by DanConwayDev** [comment]
intermittent crashing show now be fully fixed in 45dc04b81bf7c07f249c9539a48516d4c17abdba
